### ISSUE TITLE
What is dynamic feasibility?

### ISSUE THREAD

**Issue by Zentrik** [dmalyuta/scp_traj_opt#3]
To decrease cost, I lowered `wtr` but that has led to me getting 'dyn: F' indefinitely (using ptr). I am unsure of what that actually means, is it that the discretisation is in inaccurate? I increased N tenfold and it didn't seem to improve much.

I would like to know where in the code it is determined whether a trajectory is dynamically feasibly, I could only find it here   https://github.com/dmalyuta/scp_traj_opt/blob/b7dd4b9d5437c98559f73128983045915ba22423/solvers/src/discretization.jl#L207-L212 but that doesn't seem to be used other than for the initial guess/ warm start. 

Also, I got scvx working in a hacky way in my fork https://github.com/Zentrik/scp_traj_opt if you want to copy it.

**Comment by Zentrik** [comment]
Ahh the constructor is calling it in an eval, but vscode doesn't let u debug that so it would break on the discretize  function.

**Comment by Zentrik** [comment]
I thought scvx wasn't working in the jgcd branch as none of the examples seemed to use it and https://github.com/dmalyuta/scp_traj_opt/blob/b7dd4b9d5437c98559f73128983045915ba22423/solvers/src/Solvers.jl#L31-L32.
When I tried to include the scvx file manually I got a bunch of errors about the types starting with T_, if I'm remembering correctly.

**Comment by dmalyuta** [comment]
Yeah you're right -- just FYI, though, it's available in the csm branch. I have not yet made time to port SCvx and GuSTO to the new back-end code that the jgcd branch uses, but I will do that in the next 1-2 months. Thank you for opening this issue!
